server:
  port: 8525
spring:
  application:
    name: orm-generator
springdoc:
  swagger-ui:
    # 修改Swagger UI路径
    path: /swagger-ui.html
    # 开启Swagger UI界面
    enabled: true
  api-docs:
    # 修改api-docs路径
    path: /v3/api-docs
    # 开启api-docs
    enabled: true
    # 配置需要生成接口文档的扫描包
    packages-to-scan: com.msdn.generator.controller
